Feature/tinf 139 location panel component anpassen
SAKPaaS/frontend pull request #176
Opened 2020-04-29 19:25 UTC by elsholz

Übersetzung läuft und so siehts aus:
![image](https://user-images.githubusercontent.com/27976805/80637872-f11da700-8a5f-11ea-965b-75199e2443d5.png)

2020-04-29 21:05 UTC, nclskfm requested changes
hab noch n paar sachen @elsholz :)

2020-04-29 21:05 UTC, nclskfm commented on SAKPaaS/src/app/components/location-panel/location-panel.component.html
> +      <ng-container *ngIf="mockLocationsForFavorites.length > 0">
favoriten erstmal ausblenen, bis die funktionalität implementiert ist

2020-04-29 21:05 UTC, nclskfm commented on SAKPaaS/src/app/components/location-panel/location-panel.component.scss
> +  border-radius: 28px;
![image](https://user-images.githubusercontent.com/52164046/80645830-f8e34880-8a6b-11ea-965e-a80eaca2b4bb.png)

Fände es schöner, wenn man den Borderadius für die unteren Ecken entfernen würde.

2020-04-29 21:05 UTC, nclskfm commented on SAKPaaS/src/assets/i18n/de.json
> +    "closetoyou": "In der Nähe",
Die Eigenschaften bitte `close-to-you` & `search-results` nennen

2020-04-29 21:05 UTC, nclskfm commented on SAKPaaS/src/app/components/location-panel/location-panel.component.scss
> +  width: 0px;
wollen wir gar keine scrollbar mehr anzeigen? :D

2020-04-29 21:05 UTC, nclskfm commented on SAKPaaS/src/app/components/location-panel/location-panel.component.scss
> +  width: 0px;
also eine generelle Frage @DavidSchmidt00 @felixwortmann @cgomm

2020-04-29 21:05 UTC, nclskfm commented on SAKPaaS/src/app/components/location-panel/location-panel.component.html
> +        <app-location-list [locations]="locations" [listType]="searchType"></app-location-list>
![image](https://user-images.githubusercontent.com/52164046/80646276-b9692c00-8a6c-11ea-9f49-e96889efc784.png)
Das `X`-Icon ist abgeschnitten

2020-04-29 21:05 UTC, nclskfm commented on SAKPaaS/src/app/components/location-panel/location-panel.component.html
> +    <app-search-bar></app-search-bar>
Kannst du die Search-Bar vielleicht `sticky` machen? Also dass sie beim Scrollen stets da oben bleibt :)

2020-04-29 21:05 UTC, nclskfm commented on SAKPaaS/src/app/components/location-panel/location-panel.component.html
> +      <ng-container *ngIf="mockLocationsForFavorites.length > 0">
auch die Variable löschen bitte

2020-04-29 21:05 UTC, nclskfm commented on SAKPaaS/src/assets/i18n/en.json
> +    "closetoyou": "Close to you",
siehe de.json

2020-04-29 21:10 UTC, DavidSchmidt00 commented on SAKPaaS/src/app/components/location-panel/location-panel.component.scss
> +  width: 0px;
Ich glaube die würde die clean-ness des Designs bissl zerstören ^^
Oder?

2020-04-29 21:21 UTC, nclskfm commented on SAKPaaS/src/app/components/location-panel/location-panel.component.scss
> +  width: 0px;
Ja aber es gibt ja auch ganz schmale Scrollbalken, die ziemlich modern aussehen.
Also ich weiß halt nicht, was wichtiger ist. Das Vorhandensein einer Scrollbar oder die Cleanheit^^

2020-04-29 21:37 UTC, felixwortmann commented on SAKPaaS/src/app/components/location-panel/location-panel.component.scss
> +  width: 0px;
Wenn der schmal genug ist, denke ich nicht, dass der die Clean-ness zerstört, die Frage ist nur, ob der überhaupt genutzt und (wenn er so schmal ist) überhaupt gefunden wird...

2020-04-29 21:46 UTC, nclskfm commented on SAKPaaS/src/app/components/location-panel/location-panel.component.scss
> +  width: 0px;
@felixwortmann also tendenziell ist es einfach nur n bisschen css styling: https://www.w3schools.com/howto/howto_css_custom_scrollbar.asp

Hab mal schnell n Beispiel rausgesucht: https://codepen.io/devstreak/pen/dMYgeO

Man kann auch glaube ich sagen, dass die Scrollbar ganz rechts ist (also wie, wenn man n normales Fenster scrollt). Weiß jetzt nicht genau wie man das macht. Wäre vielleicht was für den nächsten Sprint - wir können mit dem aktuellen Stand eh noch nicht live gehen.

2020-04-29 21:48 UTC, felixwortmann commented on SAKPaaS/src/app/components/location-panel/location-panel.component.scss
> +  width: 0px;
Danke @nclskfm ich nehme das Mal auf und schaue dann mit @DavidSchmidt00 für den nächsten Sprint

2020-04-30 06:15 UTC, elsholz commented on SAKPaaS/src/app/components/location-panel/location-panel.component.html
> +      <ng-container *ngIf="mockLocationsForFavorites.length > 0">
Habe den entsprechenden Teil des HTML-Code dann erstmal auskommentiert und die Mock-Daten entfernt

2020-04-30 06:23 UTC, elsholz commented on SAKPaaS/src/app/components/location-panel/location-panel.component.scss
> +  width: 0px;
Solange man firefox 60.9 benutzt wird sie angezeigt 😉
Im Design war keine scrollbar hinterlegt, also zeige ich auch keine an. In meiner Firefox-Version scheint es keine Möglichkeit zu geben, eine scrollbar auszuschalten, aber in Chrome klappt es ja. Mobil wird eine kleine scrollbar eingeblendet, sieht ganz schick aus finde ich.

2020-04-30 06:40 UTC, elsholz commented on SAKPaaS/src/app/components/location-panel/location-panel.component.html
> +        <app-location-list [locations]="locations" [listType]="searchType"></app-location-list>
Habe ein Bisschen was an der Location-Card-Component verändert, jetzt wird es richtig angezeigt
![image](https://user-images.githubusercontent.com/27976805/80679943-2a84ff80-8abe-11ea-9f94-cd2f49317eec.png)

2020-04-30 06:45 UTC, elsholz commented on SAKPaaS/src/app/components/location-panel/location-panel.component.scss
> +  width: 0px;
@nclskfm So sieht das codepen Ding aus bei mir, ich glaub ich weiß jetzt sicher, dass firefox seltsam ist 😂
![image](https://user-images.githubusercontent.com/27976805/80680325-d595b900-8abe-11ea-8247-89b8d74cb93b.png)

2020-04-30 07:28 UTC, nclskfm approved these changes
tiptop 👍

2020-04-30 07:33 UTC, JustLokust approved these changes
sieht gut aus

2020-04-30 07:48 UTC, merged

2020-04-30 07:48 UTC, elsholz commented
:partying_face: