Feature/tinf 134 favorite service implementieren
SAKPaaS/frontend pull request #180
Opened 2020-05-05 13:24 UTC by patrickstecker

Ich glaube mehr muss beim Service nicht gemacht werden
fixes: https://pw-netz.atlassian.net/browse/TINF-351

2020-05-05 14:23 UTC, nclskfm requested changes

2020-05-05 14:23 UTC, nclskfm commented on SAKPaaS/src/app/core/services/favorite.service.ts
> +  getFavorites(): BehaviorSubject<Location[]> {
Da musst du ein Observable returnen @pad

2020-05-05 15:13 UTC, nclskfm approved these changes

2020-05-05 15:13 UTC, merged

2020-05-06 07:29 UTC, timgrohmann commented
Leudeee warum ist das gemerged wenn die Tests nicht gelaufen sind? @nclskfm @patrickstecker

2020-05-06 07:30 UTC, patrickstecker commented
Die test waren von location card und so wo ich nichts geändert hab🤷🏽‍♂️

2020-05-06 07:44 UTC, nclskfm commented
Naja erstens weil der PR nicht so wirklich was mit dem fehlgeschlagenen Test zu tun hat und zweitens geht der PR nicht in `develop`. Dachte da sei es egal und man kann es locker flockig auf dem 139er Branch fixen (und ich wollte endlich mit meiner Task anfangen :D). @timgrohmann

2020-05-06 07:45 UTC, timgrohmann commented
Also ich habe es mittlerweile gefixt auf 139 🦄

2020-05-06 07:50 UTC, nclskfm commented
bedankt 🚀

2020-05-06 16:38 UTC, lepathie commented
🤦🏼‍♂️