[Feature] Interaktion zwischen Karte und Location-Liste
SAKPaaS/frontend pull request #185
Opened 2020-05-06 10:41 UTC by timgrohmann

Fixes https://pw-netz.atlassian.net/browse/TINF-316

2020-05-06 17:40 UTC, nclskfm approved these changes
sieht gut aus und funktioniert auch lokal :+1: 

müsstest lediglich kurz den conflict auflösen @timgrohmann  :D

2020-05-06 18:01 UTC, elsholz requested changes

2020-05-06 18:01 UTC, elsholz commented on SAKPaaS/src/app/components/location-card/location-card.component.ts
>              } else {
Du müsstest hier villeicht noch checken, ob die ausgewählte location überhaupt noch in der Liste der angezeigten locations liegt. Sont Sind alle locations weiterhin geblurred, wenn man sich zu weit mit der Karte woanders hin bewegt

2020-05-07 06:17 UTC, timgrohmann commented on SAKPaaS/src/app/components/location-card/location-card.component.ts
>              } else {
Die Liste und die Locations auf der Karte sollten per Design immer up-to-date miteinander sein, also wenn du dich auf der Karte wegbewegst, aktualisiert sich auch die Liste.

2020-05-07 07:46 UTC, elsholz approved these changes

2020-05-07 07:46 UTC, merged