Feature/tinf 134 message not logged in
SAKPaaS/frontend pull request #191
Opened 2020-05-07 07:46 UTC by nclskfm

fixes:
- https://pw-netz.atlassian.net/browse/TINF-350

muss auf #190 warten.

2020-05-07 07:56 UTC, nclskfm commented
Falls es schon jemand anschauen möchte, das sind eigentlich nur die beiden commits von Max:
- https://github.com/SAKPaaS/frontend/pull/191/commits/878da14cc950deffce5ae436914b3563d4547ee0
- https://github.com/SAKPaaS/frontend/pull/191/commits/b87e9799bfef2f288d5af686f2bd0b51d1572724

Funktionierten sollte es, kann auch schon getestet werden.

2020-05-07 12:11 UTC, nclskfm commented
Ich kann nicht meinen PR approven, obwohl das Max assigned hat. Also müssen das noch zwei weitere approven :D

2020-05-10 15:49 UTC, cgomm requested changes

2020-05-10 15:49 UTC, cgomm commented on SAKPaaS/src/assets/i18n/de.json
> +      "not-logged-in": "Bitte logge dich, für die Nutzung der Favoriten, ein."
Ich persönlich finde den Text etwas schwer zu lesen, vielleicht wäre sowas wie 
"Bitte logge dich ein, um die Favoriten verwenden zu können"

Aber das will ich nicht allein entscheiden.

2020-05-10 17:38 UTC, elsholz commented on SAKPaaS/src/assets/i18n/de.json
> +      "not-logged-in": "Bitte logge dich, für die Nutzung der Favoriten, ein."
Ja da stimme ich dir zu. Nebensätze stören den Lesefluss, zumindest bei so kurzen Texten

2020-05-11 09:41 UTC, patrickstecker commented on SAKPaaS/src/assets/i18n/de.json
> +      "not-logged-in": "Bitte logge dich, für die Nutzung der Favoriten, ein."
Finde den text auch besser, danach aber LGTM

2020-05-11 11:48 UTC, timgrohmann requested changes

2020-05-11 11:48 UTC, timgrohmann commented on SAKPaaS/src/assets/i18n/de.json
> +      "not-logged-in": "Bitte logge dich, für die Nutzung der Favoriten, ein."
Naja, das ist halt kein Nebensatz, sondern eine Präpositionalgruppe mit zwei überflüssigen Kommas, aber sonst schön :)

2020-05-11 13:21 UTC, makr173 commented on SAKPaaS/src/assets/i18n/de.json
> +      "not-logged-in": "Bitte logge dich, für die Nutzung der Favoriten, ein."
Ist geändert

2020-05-11 14:46 UTC, cgomm reviewed
lgtm

2020-05-11 14:46 UTC, cgomm approved these changes

2020-05-12 15:07 UTC, elsholz approved these changes

2020-05-12 15:07 UTC, elsholz commented on SAKPaaS/src/assets/i18n/en.json
> +      "not-logged-in": "Please log in, before you use the favorite function."
Ich würd vielleicht das Komma da noch wegmachen

2020-05-13 08:13 UTC, merged