Feature/tinf 323 user card mobile ansicht
SAKPaaS/frontend pull request #193
Opened 2020-05-07 09:29 UTC by luisafuss

Das Verhalten der Progress-Bar beim scrollen könnte noch schöner sein, aber sonst sollte es passen.
https://pw-netz.atlassian.net/browse/TINF-323

2020-05-07 09:51 UTC, florianredmann requested changes

2020-05-07 09:51 UTC, florianredmann commented on SAKPaaS/src/app/components/home/home.component.ts
> +import {BreakpointObserver} from '@angular/cdk/layout';
Leerzeichen beachten (sollte { BreakpointObserver } sein)

2020-05-07 09:51 UTC, florianredmann commented on SAKPaaS/src/app/components/user-card/user-card.component.ts
> +import {BreakpointObserver} from '@angular/cdk/layout';
s.o.

2020-05-07 09:56 UTC, florianredmann approved these changes

2020-05-07 10:29 UTC, lepathie commented
![image](https://user-images.githubusercontent.com/15220797/81284432-625fea00-905e-11ea-82c6-26fbcf1c4ac5.png)

Can't see the component. :/

2020-05-07 10:30 UTC, luisafuss commented
> ![image](https://user-images.githubusercontent.com/15220797/81284432-625fea00-905e-11ea-82c6-26fbcf1c4ac5.png)
> 
> Can't see the component. :/

Schau mal in die Beschreibung. Du musst ins Menü und dann auf Badges

2020-05-07 10:31 UTC, lepathie commented
![image](https://user-images.githubusercontent.com/15220797/81284653-ac48d000-905e-11ea-8e73-1f9a51392bb7.png)
uhm.

2020-05-07 10:32 UTC, lepathie commented
![image](https://user-images.githubusercontent.com/15220797/81284781-db5f4180-905e-11ea-9088-b79b82ec51bd.png)

uhm.

2020-05-07 10:33 UTC, lepathie commented
![image](https://user-images.githubusercontent.com/15220797/81284839-f0d46b80-905e-11ea-8fcb-bc439836449c.png)

Uhm.

2020-05-07 10:34 UTC, lepathie commented
Currently the behavious is extremely awkward.

2020-05-07 10:36 UTC, luisafuss commented
> ![image](https://user-images.githubusercontent.com/15220797/81284781-db5f4180-905e-11ea-9088-b79b82ec51bd.png)
> 
> uhm.

Wie hast Du das hinbekommen?

2020-05-07 10:36 UTC, lepathie requested changes
Fix the awkwardness.

2020-05-07 10:38 UTC, lepathie commented
> > ![image](https://user-images.githubusercontent.com/15220797/81284781-db5f4180-905e-11ea-9088-b79b82ec51bd.png)
> > uhm.
> 
> Wie hast du das hinbekommen?


Simply by making the viewport smaller after opening the module.

2020-05-14 09:46 UTC, timgrohmann approved these changes

2020-05-14 10:35 UTC, merged