TINF-382 | Fix map for transition
SAKPaaS/frontend pull request #196
Opened 2020-05-07 14:06 UTC by florianredmann

- Fixed map sizing

2020-05-10 12:39 UTC, elsholz approved these changes

2020-05-10 14:36 UTC, elsholz requested changes
Wenn ich von Desktop auf Mobile ansicht wechsle, dann setxt sich die Größe der Karte sofort auf die volle Höhe, also bei ausgeklapptem LocationPanel. Bei der Original-Version war das nicht der Fall, da bleibt die Karte in Originalgröße. Das Problem, das sich daraus ergibt, ist, dass wenn man einen Supermarkt auswählt und dann von Deskto auf Mobil wechselt der Standort offensichtlich nicht mehr in der Mitte ist, beziehungsweise der Sichtbare Kartenbereich verschoben wird.

![image](https://user-images.githubusercontent.com/27976805/81502152-816baf80-92dc-11ea-8962-1368f36ef1d5.png)

Der ursprüngliche Kanackpunkt, dass die Karte nicht wieder kleiner wird, wenn man mit eingeklapptem LocationPanel zurück auf Desktop-Ansicht wechselt wurde behoben, aber halt ein anderes Problem eingeführt :grimacing:

2020-05-11 11:45 UTC, timgrohmann approved these changes

2020-05-11 12:39 UTC, elsholz approved these changes

2020-05-11 12:42 UTC, merged