Feature/tinf 367 save gps coordinates
SAKPaaS/frontend pull request #197
Opened 2020-05-10 19:15 UTC by nclskfm

fixes: https://pw-netz.atlassian.net/browse/TINF-384

2020-05-10 19:16 UTC, nclskfm commented
@SAKPaaS/frontend Ich bin mir noch nicht sicher, ob das die beste Umsetzung ist. Daher gebt mir gerne Feedback. :)

2020-05-11 06:20 UTC, timgrohmann commented on SAKPaaS/src/app/core/services/gps.service.ts
> +      this.updateGpsPosition();
Das wird nicht sonderlich viel machen, da `updateGpsPosition()` durch den Promise asynchron ist und desween zuerst returnt wird.

2020-05-11 06:25 UTC, timgrohmann commented on SAKPaaS/src/app/core/services/gps.service.ts
> +  public getGpsCoordinates(): Observable<PositionCoordinates> {
Benutzt du diese Funktion irgendwo, wo ich es gerade nicht sehe, oder kann die prinzipiell weg?

2020-05-11 06:30 UTC, timgrohmann requested changes
Siehe Kommentare am GpsService.

2020-05-11 07:44 UTC, nclskfm commented on SAKPaaS/src/app/core/services/gps.service.ts
> +  public getGpsCoordinates(): Observable<PositionCoordinates> {
Die sind prinzipiell für die anderen Subtasks von der Userstory

2020-05-11 07:46 UTC, nclskfm commented on SAKPaaS/src/app/core/services/gps.service.ts
> +  public getGpsCoordinates(): Observable<PositionCoordinates> {
Oder zum Beispiel haben wir im Backlog noch die Userstory die aktuelle Position mit so einem Ponöbel auf der Karte anzuzeigen :D

2020-05-11 13:00 UTC, timgrohmann approved these changes

2020-05-11 21:04 UTC, elsholz approved these changes

2020-05-11 22:13 UTC, merged