Feature/tinf 385 abstand zur tatsachlichen position
SAKPaaS/frontend pull request #198
Opened 2020-05-11 22:10 UTC by elsholz

2020-05-11 22:10 UTC, elsholz commented
(Ticket)[https://pw-netz.atlassian.net/secure/RapidBoard.jspa?rapidView=24&modal=detail&selectedIssue=TINF-385]

2020-05-11 22:19 UTC, elsholz commented
Wäre lieb, wenn ihr beim Testen darauf achtet, ob sich die Entfernungen der aktuellen GPS-Position anpassen. @nclskfm meinte, das geht am besten in Chrome :)

2020-05-11 22:28 UTC, nclskfm commented
> Wäre lieb, wenn ihr beim Testen darauf achtet, ob sich die Entfernungen der aktuellen GPS-Position anpassen. @nclskfm meinte, das geht am besten in Chrome :)

Jap, bei Chrome kann man die Koordinaten direkt in den Devtools überschreiben: https://developers.google.com/web/tools/chrome-devtools/device-mode/geolocation

2020-05-13 08:17 UTC, nclskfm requested changes
bitte noch beheben. (ich weiß gar nicht, warum hier bei "files changed" die Änderungen aus meinem Branch (zB `GpsService`) - die sind doch schon auf dem feature/TINF-139-Umsetzung-des-neuen-Designs 🤷‍♂️ 😄 

Außerdem gibt es noch einen merge conflict, den du beheben müsstest @elsholz

2020-05-13 08:17 UTC, nclskfm commented on SAKPaaS/src/app/components/location-card/location-card.component.ts
> +  @Input() location: Location;
Die ganzen Klassenvariablen (also `location`, `hide`, `blur` & `subscriptions`) sollten über dem Konstruktor stehen.  Also da wo du auch `distance$` deklariert hast.

2020-05-13 08:17 UTC, nclskfm commented on SAKPaaS/src/app/core/pipes/readableDistance.pipe.ts
> +import {Pipe, PipeTransform} from '@angular/core';
Der Filename ist falsch. Er sollte `readable-distance.pipe.ts` lauten.

2020-05-13 08:17 UTC, nclskfm commented on SAKPaaS/src/app/core/pipes/readableDistance.pipe.ts
> +    if (('' + Math.floor(dist)).length > 3) {
warum wird da immer mit `''` addiert?

Generell finde ich die Schreibweise nicht sehr schön. Das macht doch das gleiche:
```javascript
return dist > 999 ? ((dist / 1000).toFixed(1) + ' km') : (dist + ' m');
```
Oder halt alternativ  mit if-Abfrage:
```javascript
if (dist > 999) {
  return (dist / 1000).toFixed(1) + ' km';
} else {
  return dist + ' m';
}
```

2020-05-13 08:58 UTC, elsholz commented on SAKPaaS/src/app/core/pipes/readableDistance.pipe.ts
> +    if (('' + Math.floor(dist)).length > 3) {
Habs so gemacht, weil es da vorher auch so stand. Habs jetzt geändert

2020-05-13 09:14 UTC, nclskfm approved these changes
jop jetzt sieht es gut aus 👍

2020-05-13 09:40 UTC, florianredmann requested changes
Ansonsten nice

2020-05-13 09:40 UTC, florianredmann commented on SAKPaaS/src/app/components/location-list/location-list.component.ts
> +import {GpsService} from '../../core/services/gps.service';
Leerzeichen hinzufügen, es sollte { Location } sein statt {Location} (und natürlich bei den anderen beiden Zeilen)

2020-05-13 09:40 UTC, florianredmann commented on SAKPaaS/src/app/components/location-list/location-list.component.ts
> +  }
Warum die Zeilenumbrüche?

2020-05-13 09:40 UTC, florianredmann commented on SAKPaaS/src/app/core/pipes/readable-distance.pipe.ts
> +import {Pipe, PipeTransform} from '@angular/core';
s.o.

2020-05-13 09:40 UTC, florianredmann commented on SAKPaaS/src/app/shared/shared.module.ts
> +import {ReadableDistancePipe} from '../core/pipes/readable-distance.pipe';
s.o.

2020-05-13 09:48 UTC, elsholz commented on SAKPaaS/src/app/components/location-list/location-list.component.ts
> +  }
Weil WebStorm das fo formatiert 😂

2020-05-14 07:16 UTC, florianredmann approved these changes

2020-05-14 07:35 UTC, merged