Feature/tinf 387 suchergebnissenach abstandsortieren
SAKPaaS/frontend pull request #199
Opened 2020-05-12 14:58 UTC by elsholz

Die angezeigten Locations werden nach dem Abstand zum aktuellen GPS-Standpunkt angezeigt. Dabei werden bei jeder Änderung der angezeigten Locations diese komplett neu sortiert. Wenn jemand Vorschläge für ne schönere Lösung hat, dann gerne her damit. Habe außerdem das CSS von `LocationCard` etwas angepasst.

2020-05-13 08:23 UTC, nclskfm commented
Wartend auf PR #198.

2020-05-14 09:00 UTC, nclskfm requested changes
bitte noch das bearbeiten, sonst funktioniert es :+1:

2020-05-14 09:00 UTC, nclskfm commented on SAKPaaS/src/app/components/location-list/location-list.component.html
> +<div matSort (matSortChange)="sortData($event)" *ngFor="let location of locations.sort()" class="location-card">
wozu `matSort`? @elsholz 
Das nimmt man für Tabellen (und generell sollte das doch gar nichts machen, da du das Modul gar nicht importiert hast).
Warum machst du `let location of locations.sort()`? Du sortierst doch schon im `ngOnInit`

2020-05-14 09:00 UTC, nclskfm commented on SAKPaaS/src/app/components/location-list/location-list.component.ts
> +      if (actualGps !== undefined) {
kannst du den Vergleich nicht machen, bevor du anfängst zu sortieren? Wenn sie undefined **ODER** null (das schaust du gar nicht - also: `!actualGps`) kannst du ja nichts vergleichen. Dann musst du gar nicht erst anfangen zu sortieren.

2020-05-14 09:00 UTC, nclskfm commented on SAKPaaS/src/app/components/location-list/location-list.component.ts
> +  public sortData(data) {
das kann glaube weg?

2020-05-14 09:00 UTC, nclskfm commented on SAKPaaS/src/app/components/location-list/location-list.component.ts
> +      const actualGps = this.gpsService.getCurrentGpsCoordinates();
noch eine Anmerkung: Wenn der Standort sich ändert, wird die Liste nicht neu sortiert. Wenn man das wollen würde, müsste man auf das Observable `this.gpsService.getGpsCoordinates()` pipen, anstatt sich den aktuellen snapshot zu holen.

2020-05-14 09:02 UTC, elsholz commented on SAKPaaS/src/app/components/location-list/location-list.component.html
> +<div matSort (matSortChange)="sortData($event)" *ngFor="let location of locations.sort()" class="location-card">
Ja da haste Recht, das habe ich vergessen wieder zu entfernen

2020-05-14 09:52 UTC, timgrohmann commented
Fix mal noch die Linter-Errors, dann sieht's gut aus @elsholz

2020-05-14 09:54 UTC, timgrohmann commented
@elsholz Und vielleicht noch das Logging entfernen, was du hinzugefügt hast :)

2020-05-14 09:59 UTC, timgrohmann approved these changes

2020-05-14 10:27 UTC, nclskfm approved these changes
lgtm

2020-05-14 10:35 UTC, merged