Einstellungsicon in UC und mit Settings verlinken
SAKPaaS/frontend pull request #205
Opened 2020-05-14 18:41 UTC by luisafuss

https://pw-netz.atlassian.net/browse/TINF-428

2020-05-14 19:02 UTC, lepathie requested changes

2020-05-14 19:02 UTC, lepathie commented on SAKPaaS/src/app/components/sidenav/sidenav.component.html
> +      <a rel="noreferrer" href="https://auth.happyhamster.org/auth/realms/happyhamster/account/"  *ngIf="authService.getUser() | async">
A `title` would be neat.

2020-05-14 19:02 UTC, lepathie commented on SAKPaaS/src/app/components/sidenav/sidenav.component.html
> +      <a rel="noreferrer" href="https://auth.happyhamster.org/auth/realms/happyhamster/account/"  *ngIf="authService.getUser() | async">
```suggestion
      <a rel="noreferrer" href="https://auth.happyhamster.org/auth/realms/happyhamster/account/"  *ngIf="authService.getUser() | async" title="{{'sidenav.settings' | translate}}">
```

2020-05-14 19:02 UTC, lepathie commented on SAKPaaS/src/app/components/user-card/user-card.component.html
> +      <a href="https://auth.happyhamster.org/auth/realms/happyhamster/account/">
```suggestion
      <a href="https://auth.happyhamster.org/auth/realms/happyhamster/account/" title="title="{{'sidenav.settings' | translate}}"">
```

and in addition pls add it to the text-symbols. :)

2020-05-14 19:02 UTC, lepathie commented on SAKPaaS/src/assets/i18n/de.json
> +    "settings": "Einstellungen"
```suggestion
    "settings": "Benutzer-Einstellungen"
```

2020-05-14 19:02 UTC, lepathie commented on SAKPaaS/src/assets/i18n/de.json
> +    "settings": "Einstellungen"
Match the translations, pls.

2020-05-14 19:02 UTC, lepathie commented on SAKPaaS/src/assets/i18n/en.json
> +    "settings": "Usersettings"
```suggestion
    "settings": "User settings"
```

2020-05-14 19:03 UTC, lepathie requested changes

2020-05-14 19:03 UTC, lepathie commented on SAKPaaS/src/assets/i18n/de.json
> +    "search": "Ladensuche",
```suggestion
    "search": "Suche",
```

2020-05-14 19:48 UTC, lepathie commented on SAKPaaS/src/app/components/user-card/user-card.component.html
> +      <a href="https://auth.happyhamster.org/auth/realms/happyhamster/account/">
That copy'n'taste error I did here. ^^

2020-05-14 19:55 UTC, luisafuss commented on SAKPaaS/src/app/components/user-card/user-card.component.html
> +      <a href="https://auth.happyhamster.org/auth/realms/happyhamster/account/">
Already fixed

2020-05-14 20:04 UTC, lepathie requested changes
![image](https://user-images.githubusercontent.com/15220797/81979733-be61da00-962d-11ea-890f-644a90daa1e0.png)
The icon is outside the container.

2020-05-14 20:04 UTC, lepathie commented on SAKPaaS/src/app/components/sidenav/sidenav.component.html
> +          <mat-icon fontSet="material-icons" class="settings-icon">settings</mat-icon>
![image](https://user-images.githubusercontent.com/15220797/81979879-f9fca400-962d-11ea-96fb-a0d022c4f713.png)

Icon is outside container.

2020-05-14 20:04 UTC, lepathie commented on SAKPaaS/src/app/components/user-card/user-card.component.scss
> +    width: 19px;
```suggestion
```
should remove that.

2020-05-14 20:04 UTC, lepathie commented on SAKPaaS/src/app/components/user-card/user-card.component.scss
>      float: right;
Personally I'd prefer:
```suggestion
    position: absolute;
    right: 0;
```

Just makes more sense imo.

2020-05-14 20:04 UTC, lepathie commented on SAKPaaS/src/app/components/user-card/user-card.component.scss
>      float: right;
You have to add `position: relative;` to `#user-card .content` for it to work though.

2020-05-14 20:04 UTC, lepathie commented on SAKPaaS/src/app/components/user-card/user-card.component.scss
> +    width: 19px;
See earlier comment for reason.

2020-05-18 20:05 UTC, lepathie approved these changes
Now I'm happy. 🙂

2020-05-19 09:53 UTC, florianredmann approved these changes

2020-05-19 09:56 UTC, merged