TINF-432 | Fix locate-me button
SAKPaaS/frontend pull request #208
Opened 2020-05-16 13:19 UTC by florianredmann

- Fixed sizes

2020-05-17 09:39 UTC, nclskfm requested changes

2020-05-17 09:39 UTC, nclskfm commented on SAKPaaS/src/app/components/locate-button/locate-button.component.scss
> +  bottom: calc(7vh + 20px);
sieht irgendwie komisch aus ...
![image](https://user-images.githubusercontent.com/52164046/82140958-e1a9a680-9832-11ea-960c-d14041ef1026.png)

2020-05-17 15:22 UTC, nclskfm submitted a review, later dismissed
lgtm

2020-05-18 20:10 UTC, lepathie requested changes
This doesn't solve the problem at it's root. You should propably just make the container/overlay smaller on the y-axis.

2020-05-19 07:39 UTC, florianredmann commented
Ist das wirklich notwendig? Ist das nicht einfach nur ein anderer Lösungsweg?

2020-05-19 08:36 UTC, lepathie commented
Looks like you are using relative measures.
![image](https://user-images.githubusercontent.com/15220797/82304385-8b686f00-99bc-11ea-936c-596e3b999581.png)

2020-05-19 08:39 UTC, lepathie commented
![image](https://user-images.githubusercontent.com/15220797/82304468-acc95b00-99bc-11ea-8599-795933e54abc.png)
Because you are not fixing the problem at it's root, the other overlay elements are and will be still behind the control. Creating css-rules for each overlay-element individually would be a very inefficient and non-future-proof approach.  
That's why I think it is necessary to just make the container of the overlay elements smaller.

2020-05-19 09:08 UTC, lepathie requested changes
I propose some changes that should fix the problem at it's root.

2020-05-19 09:08 UTC, lepathie commented on SAKPaaS/src/app/components/locate-button/locate-button.component.scss
>    }
```suggestion
  }
  .map[_ngcontent-vvb-c82] {
      padding-bottom: 50px;
      height: calc(30vh + 50px);
  }
  .ol-unselectable, .ol-viewport {
      overflow: visible !important;
   }
```

2020-05-19 09:08 UTC, lepathie commented on SAKPaaS/src/app/components/locate-button/locate-button.component.scss
>      right: 7.5vw;
Use `px` or something like `em` here.

2020-05-19 09:08 UTC, lepathie commented on SAKPaaS/src/app/components/locate-button/locate-button.component.scss
> +    bottom: calc(7vh + 20px);
```suggestion
```

2020-05-19 09:14 UTC, lepathie commented on SAKPaaS/src/app/components/locate-button/locate-button.component.scss
>    }
`30vh` because thats the `top` of the location-panel on mobile.

2020-05-19 09:16 UTC, lepathie commented on SAKPaaS/src/app/components/locate-button/locate-button.component.scss
>    }
Makes the map Overlap by exactly 50px with the location-panel and hinders the overlays from doing so.

2020-05-19 09:19 UTC, lepathie commented
You might also want to `display: none` the `.ol-attribution` if that isn't forbidden by the policy.

2020-05-19 10:08 UTC, lepathie submitted a review, later dismissed
I am happy now. 🙂

2020-05-19 18:38 UTC, cgomm commented
> 
> 
> I am happy now. 🙂

Hast du deine Änderungen für approved erklärt..?

2020-05-19 20:00 UTC, lepathie commented
> > 
> > 
> > I am happy now. 🙂
> 
> Hast du deine Änderungen für approved erklärt..?

Yes.

2020-05-20 06:24 UTC, patrickstecker submitted a review, later dismissed
LGTM

2020-05-20 07:44 UTC, patrickstecker approved these changes
STILL BALLIN

2020-05-20 08:12 UTC, lepathie approved these changes
Delicious! 🍯

2020-05-20 08:18 UTC, merged